FROM node:18

WORKDIR /app

# Install required global dependencies
RUN npm install -g react-scripts

# Copy package.json and package-lock.json
COPY package*.json ./

# Install project dependencies
RUN npm install

# Volume will be mounted here, no need for COPY
CMD ["npm", "start"]